ALTER TABLE measurements
ADD COLUMN IF NOT EXISTS f1_hz REAL,
ADD COLUMN IF NOT EXISTS f2_hz REAL,
ADD COLUMN IF NOT EXISTS f3_hz REAL,
ADD COLUMN IF NOT EXISTS derived_from_image BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS source_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS processor VARCHAR(100);
